### ISSUE TITLE
Renaming  GrpcJsonClient_InitInsecure to  GrpcJsonClient_Init

### ISSUE THREAD

**Issue by yardov** [ni/grpc-json-client#12]
https://github.com/ni/grpc-json-client/blob/751bfdb935be3004133d8ba7dcfd738f21377475/src/grpc_json_client.h#L11

Can we rename this function and then if we ever add a secure way, we can call it "secure".

**Comment by smooresni** [comment]
renamed `InitInsecure` to `Initialize` in commit https://github.com/ni/grpc-json-client/commit/2ac7a79b8683a0ae8f8e7003aec05bd85b5bc369

**Comment by smooresni** [comment]
@yardov please close it you are good with the new name
