### ISSUE TITLE
Requiring a pre-allocated string for Read function may be difficult

### ISSUE THREAD

**Issue by ccifra** [ni/grpc-json-client#5]
In many cases you will not be able to call Read more than once to get the required size and then call again.  Instead Read could allocate the string and return it.  Then we can have a FreeString function that clients can all to free up the allocated string.

**Comment by smooresni** [comment]
I'm a bit confused on this one.  The feedback seems contrary to what many of our C drivers do.  With this implementation the user can either
1. preallocate a buffer and call read
2. call the method twice with a null buffer the first time to get the size

If we return a pointer to the string wouldn't there still need to be some buffer preallocation in the calling language with the added downside that now the user has to manually deallocate the C string?

**Comment by smooresni** [comment]
BTW i discovered a bug in the implementation so the exports side of the code will have to change a little anyway

**Comment by astarche** [comment]
There are 2 specific ways that NI C APIs handle the "call the method twice" convention:

`ivi-dance` -  [Example](https://zone.ni.com/reference/en-XX/help/370471AM-01/daqmxcfunc/daqmxaddnetworkdevice/)
`ivi-dance-with-a-twist` - [Example ](https://zone.ni.com/reference/en-XX/help/374264N-01/rfmxspecancvi/cvirfmxspecan_acpfetchabsolutepowerstrace/)

It'd be good to use one of those. That would be more consistent and you also want to double-check that the size is sufficient.

Probably `with-a-twist` so you don't need to (ab)use the return status.

**Comment by astarche** [comment]
I think we're talking about:

```python
grpc_json.write("{...}")
size = grpc_json.read(nullptr, 0)
buff = language_specific_allocate(size) # Whatever language-specific way of reserving a string buffer
grpc_json.read(buff, size)
# [.. do something with string ..]
# I'm assuming higher-level languages will free buff automatically
```

vs

```python
response = grpc_json.call("{...}")
# [.. do something with string ..]
grpc_json.free(response)
```

The first one, like @smooresni said, is what we use in other C APIs. And, therefore, other wrapper APIs (i.e., [nimipython](https://github.com/ni/nimi-python/blob/924dab875ffa31d4044c40b7ae5db05622d32b84/generated/nidcpower/nidcpower/session.py#L4621)). So, we know it works at least from a pure interop standpoint. Well, I haven't seen a matlab wrapper personally.

The second depends on the higher-level language being able to use the return value as a string AND pass it back to `grpc_json` as a pointer (AND not double free it). I'm not sure all that stuff really works or what other hoops are required to piece it together.

**Comment by yardov** [comment]
Can't we use the same rules as for 488.2... and pick a buffer size and not have to deal with all this. There must be people at NI that know about this right?

**Comment by smooresni** [comment]
> Can't we use the same rules as for 488.2... and pick a buffer size and not have to deal with all this. There must be people at NI that know about this right?

The trouble is we are returning a JSON object so returning an incomplete string is an error condition. Additionally waveforms will require very large buffers while simple messages not so much. It's hard to predict an appropriate size for a waveform buffer ahead of time.

**Comment by yardov** [comment]
But you can define a termination character and have a max buffer right?
I'm trying to dig how they do this in these documents:
https://documentation.help/NI-488.2/documentation.pdf
https://www.ni.com/pdf/manuals/370428v.pdf

It has to be a solved problem in that context right?
