### ISSUE TITLE
Consider different naming for Read/Write

### ISSUE THREAD

**Issue by astarche** [ni/grpc-json-client#6]
The RPC terminology I would expect for this is more like: `StartCall`, `FinishCall`.

Here's a similar API in gRPC C++: [ClientAsyncResponseReaderInterface](https://grpc.github.io/grpc/cpp/classgrpc_1_1_client_async_response_reader_interface.html).

Other similar examples use language-specific concepts (promises/futures/tasks) which have a similar start/finish terminology.

If `Read`/`Write` is a really good fit for the target domain, I could be OK with it.

**Comment by smooresni** [comment]
I don't think the completion is guaranteed to finish in the order of the `Finish` calls. So yeah, this is a bug.  Only way around it that I can think of is to implement the feedback in #7
