### ISSUE TITLE
Write should return a token that is used as input to read

### ISSUE THREAD

**Issue by astarche** [ni/grpc-json-client#7]
Currently the design is always operating on a single active call operation per session. Is that really sufficient? Will we never need parallel calls? From my perspective, it also makes the API difficult to understand ("Read what?").

If actual parallel calls is too complicated to implement right now, would it work to use a token but explicitly only allow one call to be in progress (i.e., `if token != _active_token return BAD_TOKEN`)

**Comment by astarche** [comment]
You're also not supporting multiple simultaneous sessions, but at least it looks like that could be supported with the current API (only implementation changes).

**Comment by astarche** [comment]
Errors could have a similar problem. Our driver APIs are implemented with something like:

1. Get the last error *for the given session*.
2. If no session is provided, get the last error *for the current thread*.

Ideally (2) is never needed or only needed on failed `Initialize`. And (1) is pretty important if you have simultaneous sessions. 

So, you could add a session param to `GetError` to address that from an API perspective. And you could just assert that the session in is the one-and-only globally active session if you want to restrict that (for now).

This seems like less of an issue. Creating a future alternate API for `GetErrorForSession` is probably fine.

**Comment by smooresni** [comment]
Combining this feedback with #6 we can make a `StartCall` method that returns a token to be passed to `FinishCall`. I also think a `BlockingCall' method would be nice to have.

**Comment by smooresni** [comment]
closing as resolved
