### ISSUE TITLE
Consider prefixing C exports

### ISSUE THREAD

**Issue by astarche** [ni/grpc-json-client#8]
Our driver APIs always prefix C API exports (i.e., `DAQmx` `RFmxSpecan_`) to act as a pseudo-namespace and avoid polluting the global namespace.

**Comment by astarche** [comment]
@ccifra I noticed that grpc-labview doesn't do this. Since neither are actually meant to be called from C/C++, maybe this isn't a real issue. If we have a different convention/preference for interop-only libraries, that's OK with me.

**Comment by smooresni** [comment]
So I presume this could be an issue if the exported methods were called from C/C++. That makes sense.  Could maybe prefix with `GrpcJsonClient_`

**Comment by smooresni** [comment]
closing as resolved
